/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.distna.domain.devicemanagement;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class NumberGenerator extends javax.swing.JFrame {

    
    private JFileChooser jFileChooser=new JFileChooser();
    private File directoryPath;
    private File randomNumbersFile;
    private int range=999999; 
    private int limit;
    private int previous;
    private  Random random = new Random();
    private StringBuffer string;
    /**
     * Creates new form NumberGenerator
     */
    public NumberGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Limit");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    	jFileChooser.showOpenDialog(rootPane);
    	
    	directoryPath=jFileChooser.getSelectedFile();
        randomNumbersFile=new File(directoryPath.getAbsolutePath()+"\\Random Numbers.txt");
    	try
    	{
    		limit=Integer.parseInt(jTextField1.getText());
    	}
    	catch (NumberFormatException num) {
			// TODO: handle exception
    		JOptionPane.showMessageDialog(null, "Please enter a numeric value.");
    		jTextField1.setText("");
		}
    	
    	PrintWriter printWriter=null;
    	  try {
  			printWriter=new PrintWriter(randomNumbersFile);
  	    
  			    for (int i = 0; i < limit; i++) 
  			    {
                                string=new StringBuffer(nextRnd()+""+nextRnd());
                                while(string.length()<3)
                                {
                                     string=new StringBuffer(nextRnd()+""+nextRnd());
                                }
  			    	if(string.length()!=12)
  			    	{
                                   
  			    		String differenceString=new String();
  			    		for (int size = 0; size < 12-string.length(); size++) {
  			    			differenceString=differenceString.concat("9");
  						}
//  			    		System.out.println("differenceString"+differenceString);
  			    		range=Integer.parseInt(differenceString);
  			    		string=string.append((nextRnd()));
  			    	}
//                                printWriter.write("6854"+string+"\r\n");
                                printWriter.println("6854"+string);
                                range=999999;
  			    	System.out.println(i+1+" "+string);
  			    }
  			    
  			    
  			  JOptionPane.showMessageDialog(null, "The file has been saved at "+randomNumbersFile.getAbsolutePath());
  	    } catch (FileNotFoundException e) {
  			// TODO Auto-generated catch block
  			e.printStackTrace();
            }
          finally
        {
            if ( printWriter != null ) 
            {
                printWriter.close();
            }
        }
    	
        
        
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    
    int nextRnd() {
		    if (previous == 0) {
                    return previous = random.nextInt(range) + 1;
                    }
                    else
                    {
		    int rnd = random.nextInt(range-1) + 1;
		    previous = (rnd < previous? rnd : rnd + 1);
		    return previous;
                    }
		  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGenerator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}
